### ISSUE TITLE
"Ablative" Parameter search

### ISSUE THREAD

**Issue by LiXiling** [ALRhub/cw2#49]
From a User Request:

```
params:
  a: 1
  b: 2
ablation:
  a: 3
  b: 4
grid:
  c: [1,2]
  ```
  
  leads to:
  
  ```
[
    [a:1, b:2, c:1],
    [a:3, b:2, c:1],
    [a:1, b:4, c:1],
    [a:1, b:2, c:2],
    [a:3, b:2, c:2],
    [a:1, b:4, c:2]
]
```

Note that runs with `a:3 b:4` are missing. Only one of the parameters at a time is exchanged. One can think of it as a "vertical" list across parameter keys, not values.
